name: TESTE SCHEDULE

on:
  push:
    branches:
      - main

  schedule:
    - cron: "*/5 * * * *"
      timezone: "America/Sao_Paulo"

  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Identificar evento
        run: |
          echo "EVENTO: ${{ github.event_name }}"
          echo "HORARIO UTC:"
          date -u
          echo "HORARIO SAO PAULO:"
          TZ=America/Sao_Paulo date
