name: TESTE SCHEDULE

on:
  schedule:
    - cron: "*/5 * * * *"
      timezone: "America/Sao_Paulo"
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Testar agendamento
        run: |
          echo "================================"
          echo "SCHEDULE FUNCIONOU!"
          echo "================================"

          echo "UTC:"
          date -u

          echo "São Paulo:"
          TZ=America/Sao_Paulo date
