name: TESTE SCHEDULE

on:
  schedule:
    - cron: "7,12,17,22,27,32,37,42,47,52,57 * * * *"
      timezone: "America/Sao_Paulo"

  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Identificar evento
        run: |
          echo "================================"
          echo "EVENTO: ${{ github.event_name }}"
          echo "SCHEDULE: ${{ github.event.schedule }}"
          echo "================================"

          echo "HORARIO UTC:"
          date -u

          echo "HORARIO SAO PAULO:"
          TZ=America/Sao_Paulo date
